version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: medisupply/frontend  # <- ajusta el nombre del repo ECR
    AWS_REGION: us-east-1              # <- ajusta la región

phases:
  pre_build:
    commands:
      - echo "Login en ECR..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO_NAME}
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c1-7 || echo "latest")
  build:
    commands:
      - echo "Construyendo imagen Docker..."
      - docker build --build-arg API_KEY=${API_KEY} --build-arg USER_POOL_ID=${USER_POOL_ID} --build-arg USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID} -t ${REPOSITORY_URI}:${IMAGE_TAG} -t ${REPOSITORY_URI}:latest .
      - echo "Pushing a ECR..."
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}:latest
      - echo "Generando Dockerrun.aws.json..."
      - |
        cat > Dockerrun.aws.json <<EOF
        {
          "AWSEBDockerrunVersion": "1",
          "Image": {
            "Name": "${REPOSITORY_URI}:${IMAGE_TAG}",
            "Update": "true"
          },
          "Ports": [
            { "ContainerPort": "80" }
          ]
        }
        EOF
artifacts:
  files:
    - Dockerrun.aws.json
